#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
source .venv/bin/activate
mkdir -p scraper1/scraper1/data/cleaned/import/backup

# Get the current date
get_current_date() {
    date +%Y-%m-%d
}
current_date=$(get_current_date)

# Get Unix timestamp
get_current_unix_timestamp() {
    date +%s
}
current_timestamp=$(get_current_unix_timestamp)

# Define spider commands
lafaekSpider="scrapy runspider scraper1/scraper1/spiders/lafaek_spider.py -o scraper1/scraper1/data/cleaned/import/Lafaek_jobs_${current_date}_${current_timestamp}.jsonl"
linkedinSpider="scrapy runspider scraper1/scraper1/spiders/linkedin_spider.py -o scraper1/scraper1/data/cleaned/import/LinkedIn_jobs_${current_date}_${current_timestamp}.jsonl"
unjobsSpider="scrapy runspider scraper1/scraper1/spiders/unjobs_spider.py -o scraper1/scraper1/data/cleaned/import/UNJobs_jobs_${current_date}_${current_timestamp}.jsonl"
vagaservisuSpider="scrapy runspider scraper1/scraper1/spiders/vagaservisu_spider.py -o scraper1/scraper1/data/cleaned/import/Vagaservisu_jobs_${current_date}_${current_timestamp}.jsonl"

# Define the output file paths
lafaekFile="scraper1/scraper1/data/cleaned/import/Lafaek_jobs_${current_date}_${current_timestamp}.jsonl"
linkedinFile="scraper1/scraper1/data/cleaned/import/LinkedIn_jobs_${current_date}_${current_timestamp}.jsonl"
unjobsFile="scraper1/scraper1/data/cleaned/import/UNJobs_jobs_${current_date}_${current_timestamp}.jsonl"
vagaservisuFile="scraper1/scraper1/data/cleaned/import/Vagaservisu_jobs_${current_date}_${current_timestamp}.jsonl"

# Run each spider
eval $lafaekSpider
eval $linkedinSpider
eval $unjobsSpider
eval $vagaservisuSpider

removeSpecialCharScript="scraper1/scraper1/scripts/removeSpecialChar.py"

process_file() {
    input_file=$1
    output_file="${input_file%.jsonl}_cleaned.jsonl"

    if [[ -f "$input_file" ]]; then
        if python $removeSpecialCharScript "$input_file" "$output_file"; then
            echo "Successfully cleaned: $output_file"
        else
            echo "Error: Failed to clean $input_file"
        fi
    else
        echo "Warning: $input_file does not exist, skipping cleaning."
    fi
}

# Process each file generated by the spiders
process_file "$lafaekFile"
process_file "$linkedinFile"
process_file "$unjobsFile"
process_file "$vagaservisuFile"

# Delete original non-cleaned files
delete_non_cleaned_files() {
    # Check if there are any files to delete
    if compgen -G "scraper1/scraper1/data/cleaned/import/*.jsonl" > /dev/null; then
        for file in scraper1/scraper1/data/cleaned/import/*.jsonl; do
            if [[ $file != *_cleaned.jsonl ]]; then
                rm "$file"
                echo "Deleted $file."
            fi
        done
    else
        echo "No files to delete."
    fi
}

delete_non_cleaned_files

# Store in database
dataStoreCommand="python scraper1/scraper1/scripts/save_to_db.py" 
eval $dataStoreCommand

# Move all files to backup
move_to_backup() {
    # Check if there are any files to move
    if compgen -G "scraper1/scraper1/data/cleaned/import/*.jsonl" > /dev/null; then
        for file in scraper1/scraper1/data/cleaned/import/*.jsonl; do
            mv "$file" scraper1/scraper1/data/cleaned/import/backup/
            echo "Moved $file to backup."
        done
    else
        echo "No files to move to backup."
    fi
}

move_to_backup

deactivate
